name: Rouge compatibility
on:
  workflow_dispatch:
  schedule:
    - cron: '27 5 * * 1'
permissions:
  contents: read
jobs:
  latest-rouge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle update rouge
      - run: bundle exec ruby script/compatibility --write
      - run: bundle exec rake test
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: rouge-compatibility
          path: |
            lib/antares/compatibility.rb
            docs/compatibility.md
